/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import JDBC.MONANDAO;
import Restaurant.Model.MONAN;
import java.util.ArrayList;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author This PC
 */
public class MONANFRAME extends javax.swing.JFrame {

    public MONANFRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtmamonan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttenmonan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdvt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtloai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        btnthem1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ MÓN ĂN");

        tbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ MÓN ĂN", "SỐ LƯỢNG", "TÊN MÓN ĂN", "DVT", "LOẠI", "GIÁ"
            }
        ));
        tbtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtableMouseClicked(evt);
            }
        });
        tbtable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tbtableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tbtable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("MÃ MÓN ĂN:");

        txtmamonan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmamonan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmamonanKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TÊN MÓN ĂN:");

        txttenmonan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DVT:");

        txtdvt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("LOẠI:");

        txtloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("GIÁ:");

        txtgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnthem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("SỐ LƯỢNG:");

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnthem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthem1.setText("HOME");
        btnthem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnthem)
                                .addGap(47, 47, 47)
                                .addComponent(btnxoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsua))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmamonan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttenmonan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdvt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtloai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnthem1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmamonan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttenmonan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthem)
                            .addComponent(btnxoa)
                            .addComponent(btnsua))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtableMouseClicked
        int selectedRow = tbtable.getSelectedRow();

        // Kiểm tra xem người dùng đã chọn dòng nào chưa
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng và hiển thị lên các ô nhập liệu
            txtmamonan.setText(tbtable.getValueAt(selectedRow, 0).toString());
            txtsoluong.setText(tbtable.getValueAt(selectedRow, 1).toString());
            txttenmonan.setText(tbtable.getValueAt(selectedRow, 2).toString());
            txtdvt.setText(tbtable.getValueAt(selectedRow, 3).toString());
            txtsoluong.setText(tbtable.getValueAt(selectedRow, 4).toString());
            txtgia.setText(tbtable.getValueAt(selectedRow, 5).toString());
        }
    }//GEN-LAST:event_tbtableMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        MONAN monan = new MONAN();
        try {          
            // Kiểm tra mã món ăn đã tồn tại hay không
            int MAMONAN = Integer.parseInt(txtmamonan.getText());
            int SOLUONG = Integer.parseInt(txtsoluong.getText());
            int GIA = Integer.parseInt(txtgia.getText());
            
            if (MONANDAO.isMAMONANTonTai(MAMONAN)) {
                JOptionPane.showMessageDialog(null, "Mã món ăn đã tồn tại. Vui lòng nhập một mã món ăn khác.");
                return; // Dừng việc thêm mới nếu mã đã tồn tại
            }

            // Kiểm tra và thêm món ăn mới
            if (txtmamonan.getText().isEmpty() || txtsoluong.getText().isEmpty() || txttenmonan.getText().isEmpty() || txtdvt.getText().isEmpty() || txtloai.getText().isEmpty() || txtgia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin.");
            } else {
                monan.setMAMONAN(MAMONAN); 
                monan.setSOLUONG(SOLUONG);
                monan.setTENMONAN(txttenmonan.getText());
                monan.setDVT(txtdvt.getText());                                            
                monan.setLOAI(txtloai.getText());
                monan.setGIA(GIA);
                MONANDAO.save(monan);

                DefaultTableModel dtm = (DefaultTableModel) tbtable.getModel();
                dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
                ArrayList<MONAN> list = MONANDAO.getAllRecords();
                for (MONAN monanObj : list) {
                    dtm.addRow(new Object[]{monanObj.getMAMONAN(), monanObj.getSOLUONG(), monanObj.getTENMONAN(), monanObj.getDVT(), monanObj.getLOAI(), monanObj.getGIA()});
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng số cho Mã món ăn.");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tbtable.getModel();
        ArrayList<MONAN> list = MONANDAO.getAllRecords();
        for (MONAN monanObj : list) {
            dtm.addRow(new Object[]{monanObj.getMAMONAN(), monanObj.getSOLUONG(), monanObj.getTENMONAN(), monanObj.getDVT(), monanObj.getLOAI(), monanObj.getGIA()});
        }

    }      
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String MAMONAN = txtmamonan.getText();

        // Gọi phương thức delete từ lớp NhanVienDAO để xóa nhân viên khỏi cơ sở dữ liệu
        MONANDAO.delete(MAMONAN);

        // Cập nhật lại bảng hiển thị dữ liệu
        DefaultTableModel dtm = (DefaultTableModel) tbtable.getModel();
        dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
        ArrayList<MONAN> list = MONANDAO.getAllRecords();
        for (MONAN monanObj : list) {
            dtm.addRow(new Object[]{monanObj.getMAMONAN(), monanObj.getSOLUONG(), monanObj.getTENMONAN(), monanObj.getDVT(), monanObj.getLOAI(), monanObj.getGIA()});
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtmamonanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmamonanKeyReleased
     
    }//GEN-LAST:event_txtmamonanKeyReleased

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void tbtableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbtableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtableComponentShown

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        int MAMONAN = Integer.parseInt(txtmamonan.getText());
        int SOLUONG = Integer.parseInt(txtsoluong.getText());
        String TENMONAN = txttenmonan.getText();
        String DVT = txtdvt.getText();
        String LOAI = txtloai.getText();
        int GIA = Integer.parseInt(txtgia.getText());

// Tạo một đối tượng món ăn mới với thông tin vừa lấy được
        MONAN monan = new MONAN();
        monan.setMAMONAN(MAMONAN);
        monan.setSOLUONG(SOLUONG);
        monan.setTENMONAN(TENMONAN);
        monan.setDVT(DVT);
        monan.setLOAI(LOAI);
        monan.setGIA(GIA);

// Gọi phương thức update từ lớp MONANDAO để cập nhật dữ liệu
        MONANDAO.update(monan);

// Cập nhật lại bảng hiển thị dữ liệu
        DefaultTableModel dtm = (DefaultTableModel) tbtable.getModel();
        dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
        ArrayList<MONAN> list = MONANDAO.getAllRecords();
        for (MONAN monanObj : list) {
            dtm.addRow(new Object[]{monanObj.getMAMONAN(), monanObj.getSOLUONG(), monanObj.getTENMONAN(), monanObj.getDVT(), monanObj.getLOAI(), monanObj.getGIA()});
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnthem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnthem1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MONANFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MONANFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MONANFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MONANFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MONANFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthem1;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtable;
    private javax.swing.JTextField txtdvt;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtloai;
    private javax.swing.JTextField txtmamonan;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenmonan;
    // End of variables declaration//GEN-END:variables
}
