/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package doan.view;


import Restaurant.Model.NhanVien;
import Restaurant.Controller.Service.NhanVienDAO;

import java.util.ArrayList;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class QLNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienForm
     */
    public QLNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtNgSinh = new javax.swing.JTextField();
        txtNgVaoLam = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 900));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Quản lý Nhân Viên");

        lbMaNV.setText("Mã NV");

        jLabel4.setText("Họ tên");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Ngày vào làm");

        jLabel8.setText("Số điện thoại");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        BtnSua.setText("Sửa");
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Tên", "Địa chỉ", "Ngày sinh", "Ngày vào làm", "SDT"
            }
        ));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(44, 44, 44)
                                .addComponent(btnXoa)
                                .addGap(60, 60, 60)
                                .addComponent(BtnSua))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNgSinh))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNgVaoLam))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSDT))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHoTen))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(BtnSua)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        NhanVien nhanvien = new NhanVien();
        try {
            // Lấy ngày hiện tại
            java.util.Date currentDate = new java.util.Date();

            // Chuyển đổi ngày hiện tại thành định dạng phù hợp
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedCurrentDate = dateFormat.format(currentDate);

            // Kiểm tra mã nhân viên đã tồn tại hay không
            int maNV = Integer.parseInt(txtMaNV.getText());
            if (NhanVienDAO.isMaNVTonTai(maNV)) {
                JOptionPane.showMessageDialog(null, "Mã nhân viên đã tồn tại. Vui lòng nhập một mã nhân viên khác.");
                return; // Dừng việc thêm mới nếu mã đã tồn tại
            }

            // Kiểm tra và thêm nhân viên mới
            if (txtMaNV.getText().isEmpty() || txtHoTen.getText().isEmpty() || txtDiaChi.getText().isEmpty() || txtNgSinh.getText().isEmpty() || txtNgVaoLam.getText().isEmpty() || txtSDT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin.");
            } else {
                nhanvien.setMaNV(maNV);
                nhanvien.setHoTen(txtHoTen.getText());
                nhanvien.setDiaChi(txtDiaChi.getText());

                // Chuyển đổi ngày vào làm từ chuỗi thành đối tượng Date
                java.util.Date parsedNgVaoLam = null;
                try {
                    parsedNgVaoLam = dateFormat.parse(txtNgVaoLam.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Sai định dạng ngày tháng năm vào làm. Vui lòng nhập lại theo định dạng yyyy-MM-dd.");
                    return;
                }

                // So sánh ngày vào làm với ngày hiện tại
                if (parsedNgVaoLam.after(currentDate)) {
                    JOptionPane.showMessageDialog(null, "Ngày vào làm không được lớn hơn ngày hiện tại.");
                    return;
                }

                // Convert thành java.sql.Date
                Date ngVaoLam = new Date(parsedNgVaoLam.getTime());

                // Chuyển đổi ngày sinh từ chuỗi thành đối tượng Date
                java.util.Date parsedNgSinh = null;
                try {
                    parsedNgSinh = dateFormat.parse(txtNgSinh.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Sai định dạng ngày tháng năm sinh. Vui lòng nhập lại theo định dạng yyyy-MM-dd.");
                    return;
                }

                // Convert thành java.sql.Date
                Date ngSinh = new Date(parsedNgSinh.getTime());

                nhanvien.setNgSinh(ngSinh);
                nhanvien.setNgVaoLam(ngVaoLam);
                nhanvien.setSDT(txtSDT.getText());

                NhanVienDAO.save(nhanvien);

                DefaultTableModel dtm = (DefaultTableModel) tbNhanVien.getModel();
                dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
                ArrayList<NhanVien> list = NhanVienDAO.getAllRecords();
                for (NhanVien nhanvienObj : list) {
                    dtm.addRow(new Object[]{nhanvienObj.getMaNV(), nhanvienObj.getHoTen(), nhanvienObj.getDiaChi(), nhanvienObj.getNgSinh(), nhanvienObj.getNgVaoLam(), nhanvienObj.getSDT()});
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng số cho Mã Nhân Viên.");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tbNhanVien.getModel();
        ArrayList<NhanVien> list = NhanVienDAO.getAllRecords();
        for (NhanVien nhanvienObj : list) {
            dtm.addRow(new Object[]{nhanvienObj.getMaNV(), nhanvienObj.getHoTen(), nhanvienObj.getDiaChi(), nhanvienObj.getNgSinh(), nhanvienObj.getNgVaoLam(), nhanvienObj.getSDT()});
        }

    }//GEN-LAST:event_formComponentShown

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed
        int maNV = Integer.parseInt(txtMaNV.getText());
        String hoTen = txtHoTen.getText();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSDT.getText();

// Kiểm tra định dạng và chuyển đổi ngày vào làm từ chuỗi thành đối tượng Date
        Date ngVaoLam = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date parsedNgVaoLam = sdf.parse(txtNgVaoLam.getText());
            ngVaoLam = new Date(parsedNgVaoLam.getTime());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sai định dạng ngày tháng năm vào làm. Vui lòng nhập lại theo định dạng yyyy-MM-dd.");
            return;
        }

// Kiểm tra định dạng và chuyển đổi ngày sinh từ chuỗi thành đối tượng Date
        Date ngSinh = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date parsedNgSinh = sdf.parse(txtNgSinh.getText());
            ngSinh = new Date(parsedNgSinh.getTime());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sai định dạng ngày tháng năm sinh. Vui lòng nhập lại theo định dạng yyyy-MM-dd.");
            return;
        }

// Kiểm tra ngày vào làm không được lớn hơn ngày hiện tại
        java.util.Date currentDate = new java.util.Date();
        if (ngVaoLam.after(currentDate)) {
            JOptionPane.showMessageDialog(null, "Ngày vào làm không được lớn hơn ngày hiện tại.");
            return;
        }

// Tạo một đối tượng NhanVien mới với thông tin vừa lấy được
        NhanVien nhanvien = new NhanVien();
        nhanvien.setMaNV(maNV);
        nhanvien.setHoTen(hoTen);
        nhanvien.setDiaChi(diaChi);
        nhanvien.setNgVaoLam(ngVaoLam);
        nhanvien.setNgSinh(ngSinh);
        nhanvien.setSDT(sdt);

// Gọi phương thức update từ lớp NhanVienDAO để cập nhật dữ liệu
        NhanVienDAO.update(nhanvien);

// Cập nhật lại bảng hiển thị dữ liệu
        DefaultTableModel dtm = (DefaultTableModel) tbNhanVien.getModel();
        dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
        ArrayList<NhanVien> list = NhanVienDAO.getAllRecords();
        for (NhanVien nhanvienObj : list) {
            dtm.addRow(new Object[]{nhanvienObj.getMaNV(), nhanvienObj.getHoTen(), nhanvienObj.getDiaChi(), nhanvienObj.getNgSinh(), nhanvienObj.getNgVaoLam(), nhanvienObj.getSDT()});
        }

    }//GEN-LAST:event_BtnSuaActionPerformed

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbNhanVien.getSelectedRow();

        // Kiểm tra xem người dùng đã chọn dòng nào chưa
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng và hiển thị lên các ô nhập liệu
            txtMaNV.setText(tbNhanVien.getValueAt(selectedRow, 0).toString());
            txtHoTen.setText(tbNhanVien.getValueAt(selectedRow, 1).toString());
            txtDiaChi.setText(tbNhanVien.getValueAt(selectedRow, 2).toString());
            txtNgSinh.setText(tbNhanVien.getValueAt(selectedRow, 3).toString());
            txtNgVaoLam.setText(tbNhanVien.getValueAt(selectedRow, 4).toString());
            txtSDT.setText(tbNhanVien.getValueAt(selectedRow, 5).toString());
        }


    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText();

        // Gọi phương thức delete từ lớp NhanVienDAO để xóa nhân viên khỏi cơ sở dữ liệu
        NhanVienDAO.delete(maNV);

        // Cập nhật lại bảng hiển thị dữ liệu
        DefaultTableModel dtm = (DefaultTableModel) tbNhanVien.getModel();
        dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
        ArrayList<NhanVien> list = NhanVienDAO.getAllRecords();
        for (NhanVien nhanvienObj : list) {
            dtm.addRow(new Object[]{nhanvienObj.getMaNV(), nhanvienObj.getHoTen(), nhanvienObj.getDiaChi(), nhanvienObj.getNgSinh(), nhanvienObj.getNgVaoLam(), nhanvienObj.getSDT()});
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgSinh;
    private javax.swing.JTextField txtNgVaoLam;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
