/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Restaurant.Model.HangHoa;
import Restaurant.Controller.Service.HangHoaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.sql.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class ThemHangHoa extends javax.swing.JFrame {

    /**
     * Creates new form ThemHangHoa
     */
    public ThemHangHoa() {
        initComponents();
        btnXacNhan.setEnabled(true);

    }

    public void validateField() {
        String hanghoa = txtTenHH.getText();
        if (!hanghoa.equals("")) {
            btnXacNhan.setEnabled(true);
        } else {
            btnXacNhan.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtMaHH = new javax.swing.JTextField();
        txtTenHH = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHangHoa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtNhaCungCap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHSD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtXoa = new javax.swing.JButton();
        txtSua = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thêm nguyên liệu");

        jLabel2.setText("Mã nguyên liệu");

        jLabel3.setText("Tên nguyên liệu");

        lbDonGia.setText("Đơn giá");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Hùy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtTenHH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenHHKeyReleased(evt);
            }
        });

        tbHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên", "Số lượng", "Đơn giá", "Nhà cung cấp", "HSD"
            }
        ));
        tbHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHangHoa);

        jLabel5.setText("Số lượng");

        jLabel9.setText("Nhà cung cấp");

        jLabel10.setText("HSD");

        txtXoa.setText("Xóa");
        txtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXoaActionPerformed(evt);
            }
        });

        txtSua.setText("Sửa");
        txtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuaActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXacNhan)
                            .addComponent(txtXoa))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSua)
                            .addComponent(btnHuy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGia)
                                    .addComponent(txtMaHH)
                                    .addComponent(txtTenHH)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNhaCungCap)
                                    .addComponent(txtHSD))
                                .addGap(36, 36, 36)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDonGia)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtXoa)
                    .addComponent(txtSua))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ThemHangHoa().setVisible(true);

    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        HangHoa hanghoa = new HangHoa();
        hanghoa.setMaHH(Integer.parseInt(txtMaHH.getText()));
        hanghoa.setTenHH(txtTenHH.getText());
        hanghoa.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        hanghoa.setGia(Integer.parseInt(txtGia.getText()));
        hanghoa.setNhaCungCap(txtMaHH.getText());
        Date HSD = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date parsedHSD = sdf.parse(txtHSD.getText());
            HSD = new Date(parsedHSD.getTime());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sai định dạng ngày tháng năm vào làm. Vui lòng nhập lại theo định dạng yyyy-MM-dd.");
            return;
        }
        hanghoa.setHSD(HSD);
   
        
     

        HangHoaDAO.save(hanghoa);

         DefaultTableModel dtm = (DefaultTableModel) tbHangHoa.getModel();
    dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
    ArrayList<HangHoa> list = HangHoaDAO.getAllRecords();
    for (HangHoa hanghoaObj : list) {
        dtm.addRow(new Object[]{hanghoaObj.getMaHH(), hanghoaObj.getTenHH(), hanghoaObj.getSoLuong(), hanghoaObj.getGia(), hanghoaObj.getNhaCungCap(), hanghoaObj.getHSD()});
    }


    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtTenHHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenHHKeyReleased
        // TODO add your handling code here
        validateField();

    }//GEN-LAST:event_txtTenHHKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tbHangHoa.getModel();
        ArrayList<HangHoa> list = HangHoaDAO.getAllRecords();
        for (HangHoa hanghoaObj : list) {
            dtm.addRow(new Object[]{hanghoaObj.getMaHH(), hanghoaObj.getTenHH(), hanghoaObj.getSoLuong(), hanghoaObj.getGia(), hanghoaObj.getNhaCungCap(), hanghoaObj.getHSD()});
        }


    }//GEN-LAST:event_formComponentShown

    private void txtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXoaActionPerformed
        // TODO add your handling code here:
              String maHH = txtMaHH.getText();

        // Gọi phương thức delete từ lớp HangHoaDAO để xóa nhân viên khỏi cơ sở dữ liệu
        HangHoaDAO.delete(maHH);

        // Cập nhật lại bảng hiển thị dữ liệu
        DefaultTableModel dtm = (DefaultTableModel) tbHangHoa.getModel();
        dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
        ArrayList<HangHoa> list = HangHoaDAO.getAllRecords();
        for (HangHoa hanghoaObj : list) {
            dtm.addRow(new Object[]{hanghoaObj.getMaHH(), hanghoaObj.getTenHH(), hanghoaObj.getSoLuong(), hanghoaObj.getGia(), hanghoaObj.getNhaCungCap(), hanghoaObj.getHSD()});
        }
        
    }//GEN-LAST:event_txtXoaActionPerformed

    private void tbHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHangHoaMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbHangHoa.getSelectedRow();

        // Kiểm tra xem người dùng đã chọn dòng nào chưa
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng và hiển thị lên các ô nhập liệu
            txtMaHH.setText(tbHangHoa.getValueAt(selectedRow, 0).toString());
            txtTenHH.setText(tbHangHoa.getValueAt(selectedRow, 1).toString());
            txtSoLuong.setText(tbHangHoa.getValueAt(selectedRow, 2).toString());
            txtGia.setText(tbHangHoa.getValueAt(selectedRow, 3).toString());
            txtNhaCungCap.setText(tbHangHoa.getValueAt(selectedRow, 4).toString());
            txtHSD.setText(tbHangHoa.getValueAt(selectedRow, 5).toString());
        }
                

    }//GEN-LAST:event_tbHangHoaMouseClicked

    private void txtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuaActionPerformed
   try {
        int maHH = Integer.parseInt(txtMaHH.getText());
        String tenHH = txtTenHH.getText();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        double gia = Double.parseDouble(txtGia.getText());
        String nhaCungCap = txtNhaCungCap.getText();
        Date HSD = Date.valueOf(txtHSD.getText()); // Chú ý: Kiểm tra xem định dạng ngày tháng có đúng không
        
        // Tạo đối tượng hàng hóa với thông tin đã chỉnh sửa
        HangHoa editedHangHoa = new HangHoa();
        editedHangHoa.setMaHH(maHH);
        editedHangHoa.setTenHH(tenHH);
        editedHangHoa.setSoLuong(soLuong);
        editedHangHoa.setGia((int) gia);
        editedHangHoa.setNhaCungCap(nhaCungCap);
        editedHangHoa.setHSD(HSD);

        // Cập nhật thông tin hàng hóa trong cơ sở dữ liệu
        HangHoaDAO.update(editedHangHoa); // Đảm bảo rằng bạn đã khai báo và khởi tạo lớp HangHoaDAO ở một nơi khác trong mã của bạn

        // Cập nhật lại bảng hiển thị
        DefaultTableModel dtm = (DefaultTableModel) tbHangHoa.getModel();
        dtm.setRowCount(0); // Xóa hết các dòng hiện có trong bảng
        ArrayList<HangHoa> list = HangHoaDAO.getAllRecords();
        for (HangHoa hanghoaObj : list) {
            dtm.addRow(new Object[]{hanghoaObj.getMaHH(), hanghoaObj.getTenHH(), hanghoaObj.getSoLuong(), hanghoaObj.getGia(), hanghoaObj.getNhaCungCap(), hanghoaObj.getHSD()});
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Dữ liệu không hợp lệ! Vui lòng nhập lại.");
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, "Định dạng ngày tháng không hợp lệ! Vui lòng nhập theo định dạng YYYY-MM-DD.");
    }
    }//GEN-LAST:event_txtSuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JTable tbHangHoa;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtMaHH;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JButton txtSua;
    private javax.swing.JTextField txtTenHH;
    private javax.swing.JButton txtXoa;
    // End of variables declaration//GEN-END:variables
}
