
import javax.swing.*;
import java.awt.*;
//import bean.BarChartExample;
import java.util.ArrayList;
import Restaurant.Model.tkDAO;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 84889
 */
public class ThongKe extends javax.swing.JFrame {
    public ThongKe() {
         
    
         setTitle("Thống kê tai chinh");
        initComponents();
        
                cardLayout = new CardLayout();
     
            jPMainThongKe.setLayout(cardLayout);
                    
    
            
            BarChartExample bieudo=new BarChartExample(dad,"Thang/Nam");
              jPMainThongKe.add(bieudo, "bieudo");
              
        setTitle("Thống kê tài chính");
           }
    
     // jPMainThongKe.add(monan, "TaiChinh");
//jPMainThongKe.add(TaiChinhPanel, "MonAn");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBTaiChinh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPMainThongKe = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCLuaCchon = new javax.swing.JComboBox<>();
        jTNam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTThang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("THỐNG");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jBThoat.setText("Thoát");
        jBThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThoatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("KÊ");
        jLabel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel5AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jBTaiChinh.setText("Thống kê");
        jBTaiChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTaiChinhActionPerformed(evt);
            }
        });

        jLabel6.setText("TÀI CHÍNH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBTaiChinh))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jBTaiChinh)
                .addGap(18, 18, 18)
                .addComponent(jBThoat)
                .addGap(10, 10, 10))
        );

        jPMainThongKe.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPMainThongKe.setPreferredSize(new java.awt.Dimension(10000, 1000));

        javax.swing.GroupLayout jPMainThongKeLayout = new javax.swing.GroupLayout(jPMainThongKe);
        jPMainThongKe.setLayout(jPMainThongKeLayout);
        jPMainThongKeLayout.setHorizontalGroup(
            jPMainThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        jPMainThongKeLayout.setVerticalGroup(
            jPMainThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCLuaCchon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thang", "Nam" }));
        jPanel3.add(jCLuaCchon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, 30));

        jTNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNamActionPerformed(evt);
            }
        });
        jPanel3.add(jTNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 50, 30));

        jLabel2.setText("Năm:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jLabel3.setText("Tháng: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setText("Lựa chọn");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 20));

        jTThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTThangActionPerformed(evt);
            }
        });
        jPanel3.add(jTThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(jPMainThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPMainThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void jTThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTThangActionPerformed

    private void jTNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNamActionPerformed

    private void jBThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThoatActionPerformed
                int option = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jBThoatActionPerformed

    private void jLabel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5AncestorAdded

    private void jBTaiChinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTaiChinhActionPerformed

        //sử lý nhập 
         int nam=0;
            int thang=0;
            String st=null;
       String luaChon= (String) jCLuaCchon.getSelectedItem();
         if(luaChon.equals("Thang"))
        {
            if( jTNam.getText().isEmpty())
               {
                 JOptionPane.showMessageDialog(null, "chưa nhập năm", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                  return;
                 }
            if(jTThang.getText().isEmpty())
                 {
                 JOptionPane.showMessageDialog(null, "Chưa nhập tháng", "lỗi", JOptionPane.INFORMATION_MESSAGE);
                 return;
                 }
            
             nam=Integer.valueOf(jTNam.getText());
             thang=Integer.valueOf(jTThang.getText());
             
             
             if(nam<0)
             {
                  JOptionPane.showMessageDialog(null, "Năm sai", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                  return;
                 
             }
             if(thang<1||thang>12)
             {
                  JOptionPane.showMessageDialog(null, "Tháng sai", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                  return;
             }
             
             st="THÁNG "+thang+" Năm "+nam;
           }else  if(luaChon.equals("Nam"))
           {
               if( jTNam.getText().isEmpty())
               {
                 JOptionPane.showMessageDialog(null, "chưa nhập năm", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                  return;
                 }
                  nam=Integer.valueOf(jTNam.getText());
                if(nam<0)
             {
                  JOptionPane.showMessageDialog(null, "Năm sai", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                  return;
             }
                     st="Năm"+nam;
           }
        ////////
        if(luaChon.equals("Thang"))
       {
            dad=doa.listTKThang(thang, nam);
       }else    dad=doa.listTKNam(nam);
        //------------cập nhật biểu đồ--------------------

BarChartExample bieudo=new BarChartExample(dad,st);
              jPMainThongKe.add(bieudo, "bieudo");
              cardLayout.show(jPMainThongKe, "bieudo");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTaiChinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTaiChinh;
    private javax.swing.JButton jBThoat;
    private javax.swing.JComboBox<String> jCLuaCchon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPMainThongKe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTNam;
    private javax.swing.JTextField jTThang;
    // End of variables declaration//GEN-END:variables
private    tkDAO doa=new tkDAO();
private   ArrayList<tkDAO> dad=new ArrayList();

   public  CardLayout cardLayout;

}
